#hash((formula . "racket@9")
      (artifact-prefix . "bottles")
      (bottle-rebuild . 1)
      (bottle-runners . (#hash((os . "macos-26"))
                         #hash((os . "ubuntu-latest")
                               (container . "ghcr.io/homebrew/brew:main"))
                         #hash((os . "ubuntu-24.04-arm")
                               (container . "ghcr.io/homebrew/brew:main"))))
      (syntax-runners . (#hash((os . "macos-15-intel")))))
