#hash((windows-repo-root . "/Users/cutiedeng/Y2026/M06/D23/win-racket")
      (runner . "windows-2022")
      (arch . "x86_64")
      (msvc-arch . "x64")
      (windows-targets . (#hash((arch . "x86_64")
                                (runner . "windows-2022")
                                (msvc-arch . "x64")
                                (inno-arch . "x64compatible"))
                          #hash((arch . "arm64")
                                (runner . "windows-11-arm")
                                (msvc-arch . "arm64")
                                (inno-arch . "arm64"))))
      (nmake-target . "plain-install")
      (build-jobs . 2)
      (portable-dir-name . "racket9")
      (artifact-prefix . "windows")
      (publish-release . #t)
      (release-repo . "CutieDeng/win-racket")
      (release-tag . "v9.3.5")
      (release-name . "Racket 9.3.5 Windows portable")
      (create-release . #t)
      (token-secret . "GITHUB_TOKEN"))
